stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:10
      shellScript: |-
        PACKAGE_VERSION=$(cat package.json \
          | grep version \
          | head -1 \
          | awk -F: '{ print $2 }' \
          | sed 's/[", ]//g')
        echo "Building HobbyFarm UI $PACKAGE_VERSION"
        npm install -g @angular/cli
        npm install
        ng build --aot
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hfui:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deploy-ui.yaml
timeout: 60
notification: {}
