language: node_js

before_script:
  - npm install -g @angular/cli # need to install angular cli in order to build

script:
  - ng build --aot
  - docker build -t "hobbyfarm/ui" . 
  - PACKAGE_VERSION=$(cat package.json \
    | grep version \
    | head -1 \
    | awk -F: '{ print $2 }' \
    | sed 's/[", ]//g')
  - docker tag "hobbyfarm/ui" "hobbyfarm/ui:$PACKAGE_VERSION
  - docker push "hobbyfarm/ui:$PACKAGE_VERSION"

services:
  - docker